// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vgpt-layouts/AgentFirst.tsx": () => import("../components/mockups/vgpt-layouts/AgentFirst.tsx"),
  "./components/mockups/vgpt-layouts/CommandCenter.tsx": () => import("../components/mockups/vgpt-layouts/CommandCenter.tsx"),
  "./components/mockups/vgpt-layouts/SplitBrain.tsx": () => import("../components/mockups/vgpt-layouts/SplitBrain.tsx")
};
